steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/auto-poster-api:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/auto-poster-api:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'auto-poster-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/auto-poster-api:$COMMIT_SHA'
      - '--region'
      - 'northamerica-northeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '100'
      - '--set-env-vars'

# Store image in Artifact Registry
images:
  - 'gcr.io/$PROJECT_ID/auto-poster-api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY