steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/auto-poster-api:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/auto-poster-api:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'auto-poster-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/auto-poster-api:$COMMIT_SHA'
      - '--region'
      - 'northamerica-northeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '100'
      - '--set-secrets'
      - 'TIKTOK_CLIENT_KEY=tiktok-client-key:latest'
      - '--set-secrets'
      - 'TIKTOK_CLIENT_SECRET=tiktok-client-secret:latest'
      - '--set-secrets'
      - 'FLASK_SECRET_KEY=flask-secret-key:latest'
      - '--set-env-vars'
      - 'TIKTOK_REDIRECT_URI=https://auto-poster-tt-57018476417.northamerica-northeast1.run.app/auth/tiktok/callback'

# Store image in Artifact Registry
images:
  - 'gcr.io/$PROJECT_ID/auto-poster-api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY