"""Add Display API fields and UserVideo model

Revision ID: 0050b508c73f
Revises: 29f431f25a00
Create Date: 2025-08-22 13:51:45.529504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0050b508c73f'
down_revision = '29f431f25a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiktok_account_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('share_url', sa.String(length=500), nullable=True),
    sa.Column('embed_link', sa.String(length=500), nullable=True),
    sa.Column('embed_html', sa.Text(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('share_count', sa.BigInteger(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tiktok_account_id'], ['tiktok_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    with op.batch_alter_table('tiktok_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_profile_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_accounts', schema=None) as batch_op:
        batch_op.drop_column('last_profile_update')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('bio')

    op.drop_table('user_videos')
    # ### end Alembic commands ###
