"""Add token management fields for TikTok API compliance

Revision ID: 29f431f25a00
Revises: 95bc99f1664f
Create Date: 2025-08-14 18:05:50.935755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f431f25a00'
down_revision = '95bc99f1664f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('scope', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('token_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_accounts', schema=None) as batch_op:
        batch_op.drop_column('token_type')
        batch_op.drop_column('scope')
        batch_op.drop_column('refresh_token_expires_at')

    # ### end Alembic commands ###
