"""Remove UserVideo model and relationship

Revision ID: 4b9762cd77c9
Revises: 5ce08bb78cef
Create Date: 2025-12-06 14:14:16.753315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b9762cd77c9'
down_revision = '5ce08bb78cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_videos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tiktok_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cover_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('share_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('embed_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('embed_html', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('like_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('comment_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('share_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_selected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tiktok_account_id'], ['tiktok_accounts.id'], name=op.f('user_videos_tiktok_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_videos_pkey')),
    sa.UniqueConstraint('video_id', name=op.f('user_videos_video_id_key'))
    )
    # ### end Alembic commands ###
