"""Add PostedVideo model for tracking posted videos

Revision ID: 5ce08bb78cef
Revises: fix_missing_columns
Create Date: 2025-12-05 17:26:19.608879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce08bb78cef'
down_revision = 'fix_missing_columns'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posted_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tiktok_account_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('privacy_level', sa.String(length=50), nullable=True),
    sa.Column('disable_duet', sa.Boolean(), nullable=True),
    sa.Column('disable_comment', sa.Boolean(), nullable=True),
    sa.Column('disable_stitch', sa.Boolean(), nullable=True),
    sa.Column('video_cover_timestamp_ms', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.String(length=100), nullable=True),
    sa.Column('publish_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tiktok_account_id'], ['tiktok_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posted_videos')
    # ### end Alembic commands ###
